Fixed some spelling mistakes 🪄

diff --git a/StarryNight/home/murphy/.local/bin/NetScope b/StarryNight/home/murphy/.local/bin/NetScope
--- a/StarryNight/home/murphy/.local/bin/NetScope
+++ b/StarryNight/home/murphy/.local/bin/NetScope
@@ -1,13 +1,13 @@
 #!/bin/bash
 
-# Simplify managing your vpn
+# Simplify managing your VPN
 Vpn() (
 
 	name="l-hetzner1-1"
 	ip="199.83.103.100"
 	
 	open_middle_man() {
-		if [ "$3" == "udp2raw" ]; then
+		if [[ "$3" == "udp2raw" ]]; then
 			udp2raw -c -l 0.0.0.0:4444 -r "$ip":2001 --cipher-mode xor --auth-mode simple --raw-mode icmp &> /dev/null &
 		else
 			forwarder -l 127.0.0.1:4444 -r "$ip":3001 -p passdg &> /dev/null &
@@ -15,14 +15,14 @@ Vpn() (
 	}
 
 	close_middle_man() {
-		if [ "$3" == "udp2raw" ]; then
+		if [[ "$3" == "udp2raw" ]]; then
 			pkill udp2raw
 		else
 			pkill forwarder
 		fi
 	}
 
-	# Prosses the subcommands
+	# Process the subcommands
 	case "${2,,}" in
 
 		"on")
@@ -64,12 +64,12 @@ Route() {
 	gateway=$(echo "$routes" | awk 'NR==1 {print $3}')
 	ip="$3"
 
-	# Check if the user provided the necessary ip address
+	# Check if the user provided the necessary IP address
 	if [[ "${2,,}" != "load" && -z "$ip" ]]; then
-		echo -e "${bred}Error: You didn't enter the required ip address!${clear}" ; exit 1 
+		echo -e "${bred}Error: You didn't enter the required IP address!${clear}" ; exit 1 
 	fi
 
-	# Prosses the subcommands
+	# Process the subcommands
 	case "${2,,}" in
 
 		"add")
@@ -92,6 +92,8 @@ Route() {
 				echo -e "${bgreen}Route ${names[$index-1]} added.${clear}"
 			done
 
+			NetScope vpn reload
+
 		;;
 
 		*)
@@ -104,7 +106,7 @@ Route() {
 
 }
 
-# Change between dns servers easily like a badbakhte irani
+# Change between DNS servers easily like a badbakhte irani
 Dns() {
 
 	case "${2,,}" in
@@ -130,7 +132,7 @@ Dns() {
 
 	esac
 
-	# Change the dns temporarily using the /etc/resolv.conf file
+	# Change the DNS temporarily using the /etc/resolv.conf file
 	echo -e "# Generated by ye badbakhte irani \\nnameserver $server1 \\nnameserver $server2" | sudo tee /etc/resolv.conf > /dev/null
 	echo -e "# Generated by ye badbakhte irani \\nsupersede domain-name-servers $server1,$server2;" | sudo tee /etc/dhclient.conf > /dev/null
 
@@ -143,7 +145,7 @@ Cycle() (
 
 	echo "Cycling through network interfaces."
 
-	# Interfaces and their ssids to loop through
+	# Interfaces and their SSIDs to loop through
 	interfaces=("Lan" "Phone" "Wifi" "Usb")
 	ssids=("M-Murphy" "P-Murphy" "I-Murphy" "S-Murphy")
 
@@ -152,7 +154,7 @@ Cycle() (
 	echo "${interfaces[@]}" | grep -wq "$active_interface" || active_interface="Usb"
 	active_interface_index=$(printf "%s\n" "${interfaces[@]}" | grep -n "$active_interface" | cut -d: -f1 | awk '{print $1 - 1}')
 
-	# loop through the next possible interfaces
+	# Loop through the next possible interfaces
 	for (( offset=1 ; offset <= 3 ; offset++ )); do
 
 		# Get the index of the next interface in the list
@@ -173,16 +175,15 @@ Cycle() (
 	echo "Interface '$active_interface' Deactivated."
 
 	NetScope route load
-	NetScope vpn reload
 
-	# Updateing eww variables to match the current interface
+	# Updating eww variables to match the current interface
 	eww update cycle_btn_class="cycle_btn_class$((next_interface_index + 1))"
 	eww update cycle_btn_status_class="cycle_btn_status_class$((next_interface_index + 1))"
 	eww update cycle_btn_status="${ssids[$next_interface_index]}"
 
 )
 
-# The function responsable for setting up namespaces
+# The function responsible for setting up namespaces
 CreateNetNS() {
 
 	# Define some variables
@@ -199,7 +200,7 @@ CreateNetNS() {
 	ip netns add "$netns"
 
 	# Make the namespace resolv.conf file
-	if [ ! -f /etc/netns/"$netns"/resolv.conf ]; then
+	if [[ ! -f /etc/netns/"$netns"/resolv.conf ]]; then
 		mkdir -p /etc/netns/"$netns"
 		cp /etc/resolv.conf /etc/netns/"$netns"/resolv.conf
 	fi
@@ -213,7 +214,7 @@ CreateNetNS() {
 		gateway=$(dhclient -v -r "$interface" 2>&1 | grep "DHCPRELEASE" | awk '{print $7}')
 	fi
 
-	# Find a free ip address to use
+	# Find a free IP address to use
 	taken_ips=$(ip -br a ; ip -all netns exec ip -br a)
 	for each_subnet in {2..255}; do
 		! echo "$taken_ips" | grep -wq "${gateway%.*}.$each_subnet" && ip="${gateway%.*}.$each_subnet" && break
@@ -227,27 +228,27 @@ CreateNetNS() {
 	ip -n "$netns" link set ipvlan up
 	ip -n "$netns" link set lo up
 
-	# Assign the ip address and the default route
+	# Assign the IP address and the default route
 	ip -n "$netns" addr add "$ip/24" dev ipvlan
 	ip -n "$netns" route add default via "$gateway"
 
-	# Make pinging don't require root access
+	# Make pinging not require root access
 	ip netns exec "$netns" sysctl net.ipv4.ping_group_range='0 2147483647' > /dev/null
 
 	echo -e "${bgreen}Created the namespace '$netns' successfully.${clear}"
 
 }
 
-# The function responsable for removing namespaces
+# The function responsible for removing namespaces
 RemoveNetNS() {
 
 	# Define some variables
 	netns="$1"
 
-	# Kill all off the prosses running in the namespace
+	# Kill all of the processes running in the namespace
 	for pid in $(ip netns pids "$netns"); do kill "$pid"; done
 
-	# Remove the namespace and it's configs
+	# Remove the namespace and its configs
 	ip netns delete "$netns"
 	rm -r /etc/netns/"$netns"
 
@@ -260,9 +261,9 @@ NetNS() {
 
 	# Get the active interface
 	interface=$(ip r | awk 'NR==1 {print $5}')
-	if [ -n "$3" ]; then interface="$3" ; fi
+	if [[ -n "$3" ]]; then interface="$3" ; fi
 
-	# Prosses the subcommands
+	# Process the subcommands
 	case "${2,,}" in
 
 		"status"|"")
@@ -288,7 +289,7 @@ NetNS() {
 						for psname in "${blacklist[@]}"; do
 							echo "$pslist" | awk "\$1 == $pid { print \$3 }" | grep -q "$psname" && continue=true && break
 						done
-						if [ "$continue" = true ]; then continue ; fi
+						if [[ "$continue" = true ]]; then continue ; fi
 
 						# Show the process using a compacted tree format
 						echo -n " └───"
@@ -301,7 +302,7 @@ NetNS() {
 							blacklist+=("$psname")
 						fi
 
-						# Fix the perivous lines '└' charachter if there is one
+						# Fix the previous line '└' character if there is one
 						if [[ "$first" == false ]]; then
 							echo -ne "\033[2A ├\033[2B\r"
 						fi
@@ -321,7 +322,7 @@ NetNS() {
 		"delete"|"remove")
 
 			# Target all interfaces if user didn't provide any
-			if [ -z "$3" ]; then interface="-" ; fi
+			if [[ -z "$3" ]]; then interface="-" ; fi
 
 			# If the name didn't end with -Num then remove all of the instances of that interface otherwise just remove the namespace with the name
 			if [[ ! "$interface" =~ -[0-9]+$ ]]; then
@@ -358,12 +359,12 @@ NetNS() {
 # NetScope NetNS integration for Rofi
 Rofi() {
 
-	# Get the inerface names
+	# Get the interface names
 	interfaces=$(ip netns | awk '{print $1}')
 	interfaces+="$(echo && networkctl 2>&1 | grep "ether\|wlan" | awk '{print $2}')"
 
 	# If we got an interface use it otherwise show the interfaces
-	if [ -n "$2" ]; then
+	if [[ -n "$2" ]]; then
 		daemon -u $(logname) -D ~ -- sudo -E NetScope NetNS Run "$2" "rofi -show drun"
 	else
 		echo "$interfaces"
@@ -377,7 +378,7 @@ bgreen='\033[1;32m'
 bred='\033[1;31m'
 
 # Make sure we have root access ;)
-if [ $(id -u) -ne 0 ]; then
+if [[ $(id -u) -ne 0 ]]; then
 	echo -e "${bred}Error: Root access required!, run using sudo -E${clear}" ; exit 1
 fi
 
@@ -423,7 +424,7 @@ case "${1,,}" in
 	;;
 
 	*)
-		echo -e "${bred}Error: Couldn't find the command'$1'!${clear}"
+		echo -e "${bred}Error: Couldn't find the command '$1'!${clear}"
 	;;
 
 esac
