Added a touch of 🎨

diff --git a/StarryNight/home/murphy/.local/bin/NetScope b/StarryNight/home/murphy/.local/bin/NetScope
--- a/StarryNight/home/murphy/.local/bin/NetScope
+++ b/StarryNight/home/murphy/.local/bin/NetScope
@@ -46,10 +46,12 @@ Vpn() (
 		;;
 
 		*)
-			echo "Error: Couldn't find the subcommand $2"	
+			echo -e "${bred}Error: Couldn't find the subcommand '$2'!${clear}" || exit 1
 		;;
 
 	esac
+
+	echo -e "${bgreen}VPN updated successfully.${clear}"
 
 )
 
@@ -64,7 +66,7 @@ Route() {
 
 	# Check if the user provided the necessary ip address
 	if [[ "${2,,}" != "load" && -z "$ip" ]]; then
-		echo "Error: You didn't enter the required ip address!" ; exit 1 
+		echo -e "${bred}Error: You didn't enter the required ip address!${clear}" ; exit 1 
 	fi
 
 	# Prosses the subcommands
@@ -87,18 +89,18 @@ Route() {
 			# Add all of the routes
 			for index in $(seq "${#names[@]}");do
 				ip r add "${ips[$index-1]}" via "$gateway" dev "$interface" &&
-				echo "Route ${names[$index-1]} added!"
+				echo -e "${bgreen}Route ${names[$index-1]} added.${clear}"
 			done
 
 		;;
 
 		*)
-			echo "Error: Couldn't find the subcommand $2"
+			echo -e "${bred}Error: Couldn't find the subcommand '$2'!${clear}"	
 		;;
 
 	esac
 
-	echo "Routes for $interface updated successfully"
+	echo "Routes for interface '$interface' updated successfully."
 
 }
 
@@ -123,7 +125,7 @@ Dns() {
 		;;
 
 		*)
-			echo "Error: Couldn't find the subcommand $2"	
+			echo -e "${bred}Error: Couldn't find the subcommand '$2'!${clear}"	
 		;;
 
 	esac
@@ -132,14 +134,14 @@ Dns() {
 	echo -e "# Generated by ye badbakhte irani \\nnameserver $server1 \\nnameserver $server2" | sudo tee /etc/resolv.conf > /dev/null
 	echo -e "# Generated by ye badbakhte irani \\nsupersede domain-name-servers $server1,$server2;" | sudo tee /etc/dhclient.conf > /dev/null
 
-	echo "DNS Updated successfully"
+	echo -e "${bgreen}DNS Updated successfully.${clear}"
 
 }
 
 # Cycle through your network interfaces activating one at a time
 Cycle() (
 
-	echo "Cycling through network interfaces!"
+	echo "Cycling through network interfaces."
 
 	# Interfaces and their ssids to loop through
 	interfaces=("enp6s0" "enp0s20f0u1" "wlp0s20f0u10" "enp0s20f0u6u1")
@@ -164,11 +166,11 @@ Cycle() (
 	# Cycle to the next available interface
 	ip l set "${interfaces[$next_interface_index]}" up || exit 1
 	dhclient "${interfaces[$next_interface_index]}" || exit 1
-	echo "Interface ${interfaces[$next_interface_index]} Activated!"
+	echo -e "${bgreen}Interface ${interfaces[$next_interface_index]} Activated.${clear}"
 
 	ip a flush dev "$active_interface"
 	pkill -f "dhclient.*$interfaces"
-	echo "Interface $active_interface Deactivated!"
+	echo "Interface $active_interface Deactivated."
 
 	NetScope route load
 	NetScope vpn reload
@@ -188,10 +190,10 @@ CreateNetNS() {
 	name="$interface-$(echo $(ip netns | grep $interface | wc -l) + 1 | bc)"
 
 	# Don't run if we're in a namespace
-	if [[ -n $(ip netns identify) ]]; then echo "Error: Cannot create a nested network namespace!" ; return 1 ; fi
+	if [[ -n $(ip netns identify) ]]; then echo -e "${bred}Error: Cannot create a nested network namespace!${clear}" ; return 1 ; fi
 
 	# Check to see if the interface provided actually exists
-	if ! ip -br l | grep -Eq "(^| )$interface($| )"; then echo "Error: Interface not found!" ; return 1 ; fi
+	if ! ip -br l | grep -Eq "(^| )$interface($| )"; then echo -e "${bred}Error: Interface '$interface' not found!${clear}" ; return 1 ; fi
 
 	# Create the namespace
 	ip netns add "$name"
@@ -232,7 +234,7 @@ CreateNetNS() {
 	# Make pinging don't require root access
 	ip netns exec "$name" sysctl net.ipv4.ping_group_range='0 2147483647' > /dev/null
 
-	echo "Succesfuly created the namespace $name!"
+	echo -e "${bgreen}Created the namespace '$name' successfully.${clear}"
 
 }
 
@@ -249,7 +251,7 @@ RemoveNetNS() {
 	ip netns delete "$interface"
 	rm -r /etc/netns/"$interface"
 
-	echo "NetNS $netns removed successfully!"
+	echo -e "${bgreen}NetNS '$netns' removed successfully.${clear}"
 
 }
 
@@ -301,7 +303,7 @@ NetNS() {
 		;;
 
 		*)
-			echo "Error: Couldn't find the subcommand $2"
+			echo -e "${bred}Error: Couldn't find the subcommand '$2'!${clear}"
 		;;
 
 	esac
@@ -324,9 +326,14 @@ Rofi() {
 
 }
 
+# Define some color variables
+clear='\033[0m'
+bgreen='\033[1;32m'
+bred='\033[1;31m'
+
 # Make sure we have root access ;)
 if [ $(id -u) -ne 0 ]; then
-	echo "Error: Root access required!, run using sudo -E" ; exit 1
+	echo -e "${bred}Error: Root access required!, run using sudo -E${clear}" ; exit 1
 fi
 
 # Main argument handler
@@ -371,7 +378,7 @@ case "${1,,}" in
 	;;
 
 	*)
-		echo "Error: Couldn't find command $1"
+		echo -e "${bred}Error: Couldn't find the command'$1'!${clear}"
 	;;
 
 esac
